Proyecto SAPS-ML: ili9341
ili9341
Drivers Programable » Drivers devices
Files
file ili9341.h
TFT LCD RGB 240x320 ILI9341 driver.
Macros
#define ILI9341_WIDTH 240
#define ILI9341_HEIGHT 320
#define ILI9341_PIXEL_MAX 76800
#define ILI9341_BLACK 0x0000 /* 0, 0, 0 */
#define ILI9341_NAVY 0x000F /* 0, 0, 128 */
#define ILI9341_DARKGREEN 0x03E0 /* 0, 128, 0 */
#define ILI9341_DARKCYAN 0x03EF /* 0, 128, 128 */
#define ILI9341_MAROON 0x7800 /* 128, 0, 0 */
#define ILI9341_PURPLE 0x780F /* 128, 0, 128 */
#define ILI9341_OLIVE 0x7BE0 /* 128, 128, 0 */
#define ILI9341_LIGHTGREY 0xC618 /* 192, 192, 192 */
#define ILI9341_DARKGREY 0x7BEF /* 128, 128, 128 */
#define ILI9341_BLUE 0x001F /* 0, 0, 255 */
#define ILI9341_BLUE2 0x051D
#define ILI9341_GREEN 0x07E0 /* 0, 255, 0 */
#define ILI9341_GREEN2 0xB723
#define ILI9341_CYAN 0x07FF /* 0, 255, 255 */
#define ILI9341_RED 0xF800 /* 255, 0, 0 */
#define ILI9341_MAGENTA 0xF81F /* 255, 0, 255 */
#define ILI9341_YELLOW 0xFFE0 /* 255, 255, 0 */
#define ILI9341_WHITE 0xFFFF /* 255, 255, 255 */
#define ILI9341_ORANGE 0xFBE4
#define ILI9341_ORANGE2 0xFD20 /* 255, 165, 0 */
#define ILI9341_GREENYELLOW 0xAFE5 /* 173, 255, 47 */
#define ILI9341_PINK 0xF81F
#define ILI9341_BROWN 0xBBCA
Enumerations
enum ili9341_orientation_t { ILI9341_Portrait_1, ILI9341_Portrait_2, ILI9341_Landscape_1, ILI9341_Landscape_2 }
Possible orientations for LCD.
Functions
uint8_t ILI9341Init (uint8_t spi_port, uint8_t gpio_cs, uint8_t gpio_dc, uint8_t gpio_rst)
Initializes ILI9341 LCD.
void ILI9341DrawPixel (uint16_t x, uint16_t y, uint16_t color)
Draws single pixel to LCD.
void ILI9341Fill (uint16_t color)
Fills entire LCD with color.
void ILI9341Rotate (ili9341_orientation_t orientation)
Rotates LCD to specific orientation.
void ILI9341DrawChar (uint16_t x, uint16_t y, char data, Font_t *font, uint16_t foreground, uint16_t background)
Draw a single character on the LCD.
void ILI9341DrawInt (uint16_t x, uint16_t y, uint32_t num, uint8_t dig, Font_t *font, uint16_t foreground, uint16_t background)
Draw an integer on the LCD.
void ILI9341DrawString (uint16_t x, uint16_t y, char *str, Font_t *font, uint16_t foreground, uint16_t background)
Draw a string on the LCD.
void ILI9341GetStringSize (char *str, Font_t *font, uint16_t *width, uint16_t *height)
Gets width and height of box with text.
void ILI9341DrawLine (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color)
Draws line on the LCD.
void ILI9341DrawRectangle (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color)
Draws rectangle on the LCD.
void ILI9341DrawFilledRectangle (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color)
Draws filled rectangle on the LCD.
void ILI9341DrawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Draws circle on the LCD.
void ILI9341DrawFilledCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Draws filled circle on the LCD.
void ILI9341DrawPicture (uint16_t x, uint16_t y, uint16_t width, uint16_t hieght, const uint8_t *pic)
Draw a picture on the LCD.
uint8_t ILI9341DeInit (void)
De-initializes ILI9341 LCD.
Detailed Description
Macro Definition Documentation
ILI9341_HEIGHT
#define ILI9341_HEIGHT 320
LCD height in pixels
Definition at line 52 of file ili9341.h.
ILI9341_WIDTH
#define ILI9341_WIDTH 240
LCD width in pixels
Definition at line 51 of file ili9341.h.
Enumeration Type Documentation
ili9341_orientation_t
enum ili9341_orientation_t
Possible orientations for LCD.
Enumerator
ILI9341_Portrait_1
Portrait orientation mode 1
ILI9341_Portrait_2
Portrait orientation mode 2
ILI9341_Landscape_1
Landscape orientation mode 1
ILI9341_Landscape_2
Landscape orientation mode 2
Definition at line 83 of file ili9341.h.
Function Documentation
ILI9341DeInit()
uint8_t ILI9341DeInit (void)
De-initializes ILI9341 LCD.
Parameters
None
Return values
1 when success, 0 when fails
ILI9341DrawChar()
void ILI9341DrawChar (uint16_t x, uint16_t y, char data, Font_t * font, uint16_t foreground, uint16_t background)
Draw a single character on the LCD.
Parameters
[in] x X position of top left corner
[in] y Y position of top left corner
[in] data Character to be displayed
[in] font Pointer to used font
[in] foreground Color for char
[in] background Color for char background
Return values
None
Definition at line 422 of file ili9341.c.
References Font_t::FontWidth, MAX_VALUE_SIZE, x, and y.
Referenced by ILI9341DrawInt(), and ILI9341DrawString().
ILI9341DrawCircle()
void ILI9341DrawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Draws circle on the LCD.
Parameters
[in] x0 X coordinate of center circle point
[in] y0 Y coordinate of center circle point
[in] r Circle radius
[in] color Circle color
Return values
None
Definition at line 658 of file ili9341.c.
References ILI9341DrawPixel(), x, and y.
ILI9341DrawFilledCircle()
void ILI9341DrawFilledCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Draws filled circle on the LCD.
Parameters
[in] x0 X coordinate of center circle point
[in] y0 Y coordinate of center circle point
[in] r Circle radius
[in] color Circle color
Return values
None
Definition at line 697 of file ili9341.c.
References ILI9341DrawLine(), ILI9341DrawPixel(), x, and y.
ILI9341DrawFilledRectangle()
void ILI9341DrawFilledRectangle (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color)
Draws filled rectangle on the LCD.
Parameters
[in] x0 X coordinate of top left point
[in] y0 Y coordinate of top left point
[in] x1 X coordinate of bottom right point
[in] y1 Y coordinate of bottom right point
[in] color Rectangle color
Return values
None
Definition at line 653 of file ili9341.c.
References Fill().
ILI9341DrawInt()
void ILI9341DrawInt (uint16_t x, uint16_t y, uint32_t num, uint8_t dig, Font_t * font, uint16_t foreground, uint16_t background)
Draw an integer on the LCD.
Parameters
[in] x X position of top left corner
[in] y Y position of top left corner
[in] num Number to be displayed
[in] dig Number of digits to display
[in] font Pointer to used font
[in] foreground Color for char
[in] background Color for char background
Return values
None
Definition at line 487 of file ili9341.c.
References Font_t::FontWidth, ILI9341DrawChar(), x, and y.
ILI9341DrawLine()
void ILI9341DrawLine (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color)
Draws line on the LCD.
Parameters
[in] x0 X coordinate of starting point
[in] y0 Y coordinate of starting point
[in] x1 X coordinate of ending point
[in] y1 Y coordinate of ending point
[in] color Line color
Return values
[in] None
Definition at line 558 of file ili9341.c.
Referenced by ILI9341DrawFilledCircle(), and ILI9341DrawRectangle().
ILI9341DrawPicture()
void ILI9341DrawPicture (uint16_t x, uint16_t y, uint16_t width, uint16_t hieght, const uint8_t * pic)
Draw a picture on the LCD.
Parameters
[in] x X position of top left corner of picture
[in] y Y position of top left corner of picture
[in] width Picture width in pixels
[in] height Picture height in pixels
[in] pic Pointer to first byte of picture
Return values
None
Definition at line 733 of file ili9341.c.
References MAX_VALUE_SIZE, MEM_WRITE, SetCursorPosition(), x, and y.
ILI9341DrawPixel()
void ILI9341DrawPixel (uint16_t x, uint16_t y, uint16_t color)
Draws single pixel to LCD.
Parameters
[in] x X position for pixel
[in] y Y position for pixel
[in] color Color of pixel
Return values
None
Definition at line 371 of file ili9341.c.
References HighByte, LowByte, MEM_WRITE, SetCursorPosition(), WriteLCD(), x, and y.
Referenced by ILI9341DrawCircle(), and ILI9341DrawFilledCircle().
ILI9341DrawRectangle()
void ILI9341DrawRectangle (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color)
Draws rectangle on the LCD.
Parameters
[in] x0 X coordinate of top left point
[in] y0 Y coordinate of top left point
[in] x1 X coordinate of bottom right point
[in] y1 Y coordinate of bottom right point
[in] color Rectangle color
Return values
None
Definition at line 645 of file ili9341.c.
References ILI9341DrawLine().
ILI9341DrawString()
void ILI9341DrawString (uint16_t x, uint16_t y, char * str, Font_t * font, uint16_t foreground, uint16_t background)
Draw a string on the LCD.
Parameters
[in] x X position of top left corner of first character in string
[in] y Y position of top left corner of first character in string
[in] str Pointer to first character
[in] font Pointer to used font
[in] foreground Color for string
[in] background Color for string background
Return values
None
Definition at line 505 of file ili9341.c.
References Font_t::FontHeight, Font_t::FontWidth, ILI9341DrawChar(), x, and y.
ILI9341Fill()
void ILI9341Fill (uint16_t color)
Fills entire LCD with color.
Parameters
[in] color Color to be used in fill
Return values
None
Definition at line 380 of file ili9341.c.
References Fill().
ILI9341GetStringSize()
void ILI9341GetStringSize (char * str, Font_t * font, uint16_t * width, uint16_t * height)
Gets width and height of box with text.
Parameters
[in] str Pointer to first character
[in] font Pointer to used font
[out] width Pointer to variable to store width
[out] height Pointer to variable to store height
Return values
None
Definition at line 544 of file ili9341.c.
References Font_t::FontHeight, and Font_t::FontWidth.
ILI9341Init()
uint8_t ILI9341Init (uint8_t spi_port, uint8_t gpio_cs, uint8_t gpio_dc, uint8_t gpio_rst)
Initializes ILI9341 LCD.
Parameters
[in] spi_port Number of SPI port connected to LCD driver
[in] gpio_cs Number of GPIO pin to use as chip select
[in] gpio_dc Number of GPIO pin to use as data/command
[in] gpio_rst Number of GPIO pin to use as hardware reset
Return values
1 when success, 0 when fails
Definition at line 331 of file ili9341.c.
ILI9341Rotate()
void ILI9341Rotate (ili9341_orientation_t orientation)
Rotates LCD to specific orientation.
Parameters
[in] orientation LCD orientation
Return values
None
< Row Address Order (MY) = 0, Column Address Order (MX) = 1, Row/Column Exchange (MV) = 0
< Row Address Order (MY) = 1, Column Address Order (MX) = 1, Row/Column Exchange (MV) = 0
< Row Address Order (MY) = 0, Column Address Order (MX) = 0, Row/Column Exchange (MV) = 1
< Row Address Order (MY) = 1, Column Address Order (MX) = 1, Row/Column Exchange (MV) = 1
Definition at line 385 of file ili9341.c.
References ILI9341_Portrait_1.