Proyecto SAPS-ML: Aplicación
Aplicación
Macros
#define ARM_MATH_CM4
#define __FPU_PRESENT 1
#define abs(a) (((a) < (0)) ? (-a) : (a))
#define FILTER
Luego de obtenido los coeficientes del filtro descomentar esta linea para.
#define INFERRINGML
Luego de obtenido el modelo de inferencia descomentar esta linea para.
#define ADXL335
Acelerómetro a utilizar.
#define NUM_AXES 3
Número de ejes.
#define ACCEL_THRESHOLD 0.5
Umbral inicio de movimiento.
#define SAMPLE_FREC 500
Frecuencia de muestreo.
#define SAMPLE_FREC_MS (1000/SAMPLE_FREC)
#define TIME_SAMPLE 3
Duración del movimiento.
#define NUM_SAMPLES (TIME_SAMPLE*SAMPLE_FREC)
Cantidad de muestras.
Enumerations
enum state_t { DATALOGGING = 0, INFERRING, RECORD, DATALOGGING_THR }
Enumeraciones de las máquinas de estado.
enum state_rec_t { WAITING_REC = 0, END_REC, LOGGING_REC }
Functions
unsigned long Pow (long V, uint8_t shift)
uint8_t * ftos (uint8_t W, uint8_t D, float data_n)
Función para pasar de flotante a string.
void Switch1 (void)
Función para el servicio de interrupción de la tecla 1, activa el envío de tiempos de ejecución.
void Switch3 (void)
Función para el servicio de interrupción de la tecla 3, pasa al modo grabación.
void Switch2 (void)
Función para detección de movimiento.
void Switch4 (void)
Función para el servicio de interrupción de la tecla 4, pasa al modo inferencia.
bool motionDetected (float ax, float ay, float az)
void Process ()
Función para el servicio de interrupción del Timer, adquisición y procesamiento de los datos.
int main (void)
Variables
uint16_t x
Aceleración triaxial, eje x, entero.
uint16_t y
Aceleración triaxial, eje y, entero.
uint16_t z
Aceleración triaxial, eje z, entero.
float x_G
Aceleración triaxial, eje x, flotante.
float y_G
Aceleración triaxial, eje y, flotante.
float z_G
Aceleración triaxial, eje z, flotante.
float x_G_filt
Aceleración triaxial filtrada, eje x.
float y_G_filt
Aceleración triaxial filtrada, eje y.
float z_G_filt
Aceleración triaxial filtrada, eje z.
serial_config UART_USB
Estructura de configuración de la UART.
state_t state
Variable para máquina de estado principal.
state_rec_t record_state
Variable para máquina de estado de grabación de movimientos.
uint16_t frame =0
Variable auxiliar, lleva la cuenta de los "frames" triaxiales enviados.
float features [(int)(NUM_SAMPLES *NUM_AXES)]
arm_biquad_cascade_df2T_instance_f32 IIR1_x
Instancia de la estructura de datos para filtro IIR, eje x.
arm_biquad_cascade_df2T_instance_f32 IIR1_y
Instancia de la estructura de datos para filtro IIR, eje y.
arm_biquad_cascade_df2T_instance_f32 IIR1_z
Instancia de la estructura de datos para filtro IIR, eje z.
float32_t IIRstate_x [2 *STAGES]
Arreglo para los estados del filtro del eje x (dos por cada etapa).
float32_t IIRstate_y [2 *STAGES]
Arreglo para los estados del filtro del eje y (dos por cada etapa).
float32_t IIRstate_z [2 *STAGES]
Arreglo para los estados del filtro del eje z (dos por cada etapa).
Detailed Description
Function Documentation
ftos()
uint8_t * ftos (uint8_t W, uint8_t D, float data_n)
Función para pasar de flotante a string.
Parameters
[in] W Cantidad de cifras a la izquierda del punto decimal.
[in] D Cantidad de cifras a la derecha del punto decimal.
[in] data_n Valore a convertir.
Returns
Puntero al string con el valor convertido
Definition at line 156 of file main.c.
Referenced by Switch3().
Process()
void Process ()
Función para el servicio de interrupción del Timer, adquisición y procesamiento de los datos.
Parameters
[in] No hay parámetros
Returns
No hay parámetros
Definition at line 291 of file main.c.
References IIR1_x, IIR1_y, IIR1_z, ReadXValue(), ReadYValue(), ReadZValue(), state, x, x_G, x_G_filt, y, y_G, y_G_filt, z, z_G, and z_G_filt.
Switch1()
void Switch1 (void)
Función para el servicio de interrupción de la tecla 1, activa el envío de tiempos de ejecución.
Parameters
[in] No hay parámetros
Returns
No hay parámetros
Definition at line 205 of file main.c.
References serial_config::port, state, and UART_USB.
Switch2()
void Switch2 (void)
Función para detección de movimiento.
Función para el servicio de interrupción de la tecla 2, pasa al modo datalogging.
Parameters
[in] ax Valores de aceleración en X
[in] ay Valores de aceleración en Y
[in] az Valores de aceleración en Z
Returns
True o False
Parameters
[in] No hay parámetros
Returns
No hay parámetros
Definition at line 239 of file main.c.
References serial_config::port, state, and UART_USB.
Switch3()
void Switch3 (void)
Función para el servicio de interrupción de la tecla 3, pasa al modo grabación.
Parameters
[in] No hay parámetros
Returns
No hay parámetros
Definition at line 221 of file main.c.
References ACCEL_THRESHOLD, ftos(), serial_config::port, SAMPLE_FREC, state, TIME_SAMPLE, and UART_USB.
Switch4()
void Switch4 (void)
Función para el servicio de interrupción de la tecla 4, pasa al modo inferencia.
Parameters
[in] No hay parámetros
Returns
No hay parámetros
Definition at line 255 of file main.c.
References serial_config::port, state, and UART_USB.