Proyecto SAPS-ML: GPIO
GPIO
Drivers Programable » Drivers microcontroller
Bare Metal driver for gpio in the EDU-CIAA board.
Files
file gpio.h
Driver Bare Metal para los pulsadores y teclas de la EDU-CIAA.
Data Structures
struct digitalIO
Macros
#define GPIOCleanInt(gp) Chip_PININT_ClearIntStatus(LPC_GPIO_PIN_INT, PININTCH(gp))
Limpia la interrupcion de cada pin.
Enumerations
enum io_t { GPIO_INPUT = 0, GPIO_OUTPUT }
enum gpio_t {
GPIO_TEC_1 =0, GPIO_TEC_2, GPIO_TEC_3, GPIO_TEC_4,
GPIO_LED_1, GPIO_LED_2, GPIO_LED_3, GPIO_LED_RGB_R,
GPIO_LED_RGB_G, GPIO_LED_RGB_B, GPIO_LCD_1, GPIO_LCD_2,
GPIO_LCD_3, GPIO_LCD_4, GPIO_1, GPIO_3,
GPIO_5, GPIO_LCD_EN, GPIO_LCD_RS, GPIO_T_COL0,
GPIO_T_COL1, GPIO_T_FIL0, GPIO_T_FIL2, GPIO_T_FIL3
}
Define los puertos de la EDU-CIAA.
enum gpiogp_t {
GPIOGP0 =0, GPIOGP1, GPIOGP2, GPIOGP3,
GPIOGP4, GPIOGP5, GPIOGP6, GPIOGP7
}
Define los grupos de interrupciones.
enum gpiogroupgp_t { GPIOGROUPGP0 =0, GPIOGROUPGP1 }
Define los grupos de interrupciones.
Functions
void GPIOInit (gpio_t pin, io_t io)
void GPIOOn (gpio_t pin)
Pone a 1 un pin de la EDU-CIAA.
void GPIOOff (gpio_t pin)
Apaga un pin de la EDU-CIAA.
void GPIOState (gpio_t pin, bool state)
void GPIOToggle (gpio_t pin)
Invierte el estado de un pin de la EDU-CIAA.
bool GPIORead (gpio_t pin)
Lectura de un pin de la EDU-CIAA.
void GPIOActivInt (gpiogp_t gp, gpio_t pin, void *ptr_int_func, bool edge)
Activa la interrupcion de un pin en particular y se la asigna a un grupo de interrupciones definido en gpiogp_t.
void GPIOActivGroupInt (gpiogroupgp_t group_gp, gpio_t *pins, uint8_t n_pins, void *ptr_int_func, bool edge)
Activate group interrupts and add to the interruption the chosen gpio through the vector.
void GPIODeinit (void)
Deinicializacion de los puertos GPIO de la EDU-CIAA.
void GPIO0_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO1_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO2_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO3_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO4_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO5_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO6_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO7_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GINT0_IRQHandler (void)
Interruption function of a group of gpio entries. Call the indicated function.
void GINT1_IRQHandler (void)
Variables
const digitalIO gpio []
void(* ptr_GPIO_int_func [8])()
void(* ptr_GPIO_group_int_func [2])()
Detailed Description
Bare Metal driver for gpio in the EDU-CIAA board.
/**
Macro Definition Documentation
GPIOCleanInt
GPIOCleanInt (gp) Chip_PININT_ClearIntStatus(LPC_GPIO_PIN_INT, PININTCH(gp))
Limpia la interrupcion de cada pin.
Parameters
[in] gp Indica de que pin va a limpiar la interrupcion
Definition at line 170 of file gpio.h.
Referenced by GPIO0_IRQHandler(), GPIO1_IRQHandler(), GPIO2_IRQHandler(), GPIO3_IRQHandler(), GPIO4_IRQHandler(), GPIO5_IRQHandler(), GPIO6_IRQHandler(), and GPIO7_IRQHandler().
Enumeration Type Documentation
gpio_t
enum gpio_t
Define los puertos de la EDU-CIAA.
Enumerator
GPIO_TEC_1
Mapeo GPIO0[4] en P1_0
GPIO_TEC_2
Mapeo GPIO0[8] en P1_1
GPIO_TEC_3
Mapeo GPIO0[9] en P1_2
GPIO_TEC_4
Mapeo GPIO1[9] en P1_6
GPIO_LED_1
Mapeo GPIO0[14] en P2_10
GPIO_LED_2
Mapeo GPIO1[11] en P2_11
GPIO_LED_3
Mapeo GPIO1[12] en P2_12
GPIO_LED_RGB_R
Mapeo GPIO5[0] en P2_0
GPIO_LED_RGB_G
Mapeo GPIO5[1] en P2_1
GPIO_LED_RGB_B
Mapeo GPIO5[2] en P2_2
GPIO_LCD_1
Mapeo GPIO2[4] en P4_4
GPIO_LCD_2
Mapeo GPIO2[5] en P4_5
GPIO_LCD_3
Mapeo GPIO2[6] en P4_6
GPIO_LCD_4
Mapeo GPIO5[14] en P4_10
GPIO_1
Mapeo GPIO5[14] en P4_10
GPIO_3
Mapeo GPIO5[14] en P4_10
GPIO_5
Mapeo GPIO5[14] en P4_10
GPIO_LCD_EN
Mapeo GPIO5[13] en P4_9
GPIO_LCD_RS
Mapeo GPIO5[12] en P4_8
GPIO_T_COL0
Mapeo GPIO1[8] en P1_5
GPIO_T_COL1
Mapeo GPIO1[8] en P1_5
GPIO_T_FIL0
Mapeo GPIO2[2] en P4_2
GPIO_T_FIL2
Mapeo GPIO2[2] en P4_2
GPIO_T_FIL3
Mapeo GPIO2[3] en P4_3
Definition at line 77 of file gpio.h.
gpiogp_t
enum gpiogp_t
Define los grupos de interrupciones.
Enumerator
GPIOGP0
Grupo de interrupciones GPIO0_IRQHandler 32
GPIOGP1
Grupo de interrupciones GPIO1_IRQHandler 33
GPIOGP2
Grupo de interrupciones GPIO2_IRQHandler 34
GPIOGP3
Grupo de interrupciones GPIO3_IRQHandler 35
GPIOGP4
Grupo de interrupciones GPIO4_IRQHandler 36
GPIOGP5
Grupo de interrupciones GPIO5_IRQHandler 37
GPIOGP6
Grupo de interrupciones GPIO6_IRQHandler 38
GPIOGP7
Grupo de interrupciones GPIO7_IRQHandler 39
Definition at line 107 of file gpio.h.
gpiogroupgp_t
enum gpiogroupgp_t
Define los grupos de interrupciones.
Enumerator
GPIOGROUPGP0
Grupo de interrupciones GPIO0_IRQHandler 32
GPIOGROUPGP1
Grupo de interrupciones GPIO1_IRQHandler 33
Definition at line 121 of file gpio.h.
Function Documentation
GPIOActivGroupInt()
void GPIOActivGroupInt (gpiogroupgp_t group_gp, gpio_t * pins, uint8_t n_pins, void * ptr_int_func, bool edge)
Activate group interrupts and add to the interruption the chosen gpio through the vector.
Parameters
[in] group_gp
[in] pins
[in] n_pins
[in] ptrIntFunc Function to be called in the interruption.
[in] edge
Definition at line 210 of file gpio.c.
References ptr_GPIO_group_int_func.
GPIOActivInt()
void GPIOActivInt (gpiogp_t gp, gpio_t pin, void * ptr_int_func, bool edge)
Activa la interrupcion de un pin en particular y se la asigna a un grupo de interrupciones definido en gpiogp_t.
Parameters
[in] gp Indica a que grupo de interrupciones se asigna al pin
[in] pin Pin que va a interrumpir
[in] void *ptr_int_func Funcion a la que se va a llamar en la interrupcion
[in] bool edge 1 si es flanco ascendente y 0 si es descendente
Definition at line 193 of file gpio.c.
References ptr_GPIO_int_func.
GPIOOff()
void GPIOOff (gpio_t pin)
Apaga un pin de la EDU-CIAA.
Parameters
[in] pin Pin que se desea poner a 0
Definition at line 173 of file gpio.c.
Referenced by ADS1299PinLow(), HcSr04ReadDistanceInCentimeters(), HcSr04ReadDistanceInInches(), LcdItsE0803Off(), LcdItsE0803Write(), and LedsOffAll().
GPIOOn()
void GPIOOn (gpio_t pin)
Pone a 1 un pin de la EDU-CIAA.
Parameters
[in] pin Pin que se desea poner a 1
Definition at line 168 of file gpio.c.
Referenced by ADS1299PinHigh(), HcSr04ReadDistanceInCentimeters(), HcSr04ReadDistanceInInches(), LcdItsE0803Off(), LcdItsE0803Write(), and SetChipSelect().
GPIORead()
bool GPIORead (gpio_t pin)
Lectura de un pin de la EDU-CIAA.
Parameters
[in] pin Pin a leer el estado
Returns
Booleano que indica el estado del pin
Definition at line 188 of file gpio.c.
Referenced by ADS1299IsDataReady(), HcSr04ReadDistanceInCentimeters(), HcSr04ReadDistanceInInches(), SwitchesRead(), and Tcrt5000ReadState().
GPIOToggle()
void GPIOToggle (gpio_t pin)
Invierte el estado de un pin de la EDU-CIAA.
Parameters
[in] pin Pin que se desea invertir
Definition at line 183 of file gpio.c.
Variable Documentation
gpio
const digitalIO gpio[]
Initial value:
=
{
    {0x01, 0x00, 0x00, 0x04, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x01, 0x01, 0x00, 0x08, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x01, 0x02, 0x00, 0x09, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x01, 0x06, 0x01, 0x09, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x02, 0x0A, 0x00, 0x0E, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x02, 0x0B, 0x01, 0x0B, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x02, 0x0C, 0x01, 0x0C, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x02, 0x00, 0x05, 0x00, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x02, 0x01, 0x05, 0x01, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x02, 0x02, 0x05, 0x02, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x04, 0x04, 0x02, 0x04, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x05, 0x02, 0x05, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x06, 0x02, 0x06, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x0A, 0x05, 0x0E, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x06, 0x04, 0x03, 0x03, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x06, 0x07, 0x05, 0x0F, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x06, 0x09, 0x03, 0x05, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x09, 0x05, 0x0D, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x04, 0x08, 0x05, 0x0C, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x01, 0x05, 0x01, 0x08, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x07, 0x04, 0x03, 0x0C, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x00, 0x02, 0x00, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x02, 0x02, 0x02, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x03, 0x02, 0x03, MD_PUP|MD_EZI|MD_ZI|FUNC0}
}
Definition at line 121 of file gpio.c.
ptr_GPIO_group_int_func
void(* ptr_GPIO_group_int_func[2])()
Pointer to the function to be called at the interruption of a group of GPIOs
Definition at line 151 of file gpio.c.
Referenced by GINT0_IRQHandler(), and GPIOActivGroupInt().
ptr_GPIO_int_func
void(* ptr_GPIO_int_func[8])()
Pointer to the function to be called at the interruption of each GPIO
Definition at line 150 of file gpio.c.
Referenced by GPIO0_IRQHandler(), GPIO1_IRQHandler(), GPIO2_IRQHandler(), GPIO3_IRQHandler(), GPIO4_IRQHandler(), GPIO5_IRQHandler(), GPIO6_IRQHandler(), GPIO7_IRQHandler(), and GPIOActivInt().