Proyecto SAPS-ML: Analog IO
Analog IO
Drivers Programable » Drivers devices
Data Structures
struct analog_input_config
Macros
#define CH0 1 /*Board connector: DAC pin*/
AD Converter Bare Metal driver for the peripheral in the EDU-CIAA Board.
#define CH1 2 /*Board connector: CH1 pin*/
#define CH2 4 /*Board connector: CH2 pin*/
#define CH3 8 /*Board connector: CH3 pin*/
#define DAC 0 /*Board connector: DAC pin. Override CH0 declaration*/
#define AINPUTS_SINGLE_READ 0
#define AINPUTS_BURST_READ 1
#define ANALOG_INPUT_READ 1
#define ANALOG_OUTPUT_WROTE 1
#define ERROR_CHANNEL_SELECTION 0
#define ANALOG_OUTPUT_RANGE 1023
Functions
void AnalogInputInit (analog_input_config *inputs)
Single analog input initialization.
void AnalogOutputInit (void)
Analog output initialization - DAC.
void AnalogInputReadPolling (uint8_t channel, uint16_t *value)
void AnalogStartConvertion (void)
Start convertion for ADC0 module.
void AnalogInputRead (uint8_t channel, uint16_t *value)
uint8_t AnalogOutputWrite (uint16_t value)
Digital-to-Analog convert - DAC pin.
Detailed Description
Macro Definition Documentation
CH0
#define CH0 1 /*Board connector: DAC pin*/
AD Converter Bare Metal driver for the peripheral in the EDU-CIAA Board.
This is a driver to control the peripheral Analogs Inputs/Outputs
Definition at line 71 of file analog_io.h.
Function Documentation
AnalogInputInit()
void AnalogInputInit (analog_input_config * inputs)
Single analog input initialization.
Parameters
[in] inputs Initilization parameters struct: channel
Returns
null
Single analog input initialization.
max 409 KHz
Definition at line 77 of file analog_io.c.
References CH0, analog_input_config::input, and analog_input_config::pAnalogInput.
Referenced by ReadXValue(), ReadYValue(), and ReadZValue().
AnalogInputReadPolling()
void AnalogInputReadPolling (uint8_t channel, uint16_t * value)
Start Acquisition
Conversion complete, and value reading
Conversion complete, and value reading
Conversion complete, and value reading
Conversion complete, and value reading
Definition at line 142 of file analog_io.c.
References CH0.
AnalogOutputInit()
void AnalogOutputInit (void)
Analog output initialization - DAC.
Returns
null
DAC function selection
DAC initialization
Definition at line 130 of file analog_io.c.
AnalogOutputWrite()
void AnalogOutputWrite (uint16_t value)
Digital-to-Analog convert - DAC pin.
Parameters
[in] value Digital value to convert
Returns
null
Definition at line 196 of file analog_io.c.
AnalogStartConvertion()
void AnalogStartConvertion (void)
Start convertion for ADC0 module.
Returns
null
Definition at line 171 of file analog_io.c.