Proyecto SAPS-ML: Systick
Systick
Drivers Programable » Drivers microcontroller
Files
file systick.h
Functions
bool SystickInit (uint32_t ms, void *ptrIntFunc)
Inicializacion del timer Systick.
void SystickDeinit (void)
Deshabilita la interrupcion del systick.
void SystickCounter (void)
Decrementa un contador en caso que los ms sean mayores que lo que puede manejar el systick.
void SysTick_Handler (void)
Funcion de interrupcion del Systick, llama a una funcion periodicamente.
Variables
void(* ptrSystickFunc)()
void(* ptrContadorFunc)()
Detailed Description
Function Documentation
SystickDeinit()
void SystickDeinit (void)
Deshabilita la interrupcion del systick.
< Desactiva Systick
Definition at line 109 of file systick.c.
SystickInit()
bool SystickInit (uint32_t ms, void * ptrIntFunc)
Inicializacion del timer Systick.
Parameters
[in] ms Indica cada cuantos milisegundos se va a llamar a la funcion
[in] ptrIntFunc Funcion a la que se va a llamar periodicamente
Returns
Booleano que indica si se pudo inicializar el systick
Definition at line 63 of file systick.c.
References ptrContadorFunc, ptrSystickFunc, and SystickCounter().
Variable Documentation
ptrContadorFunc
void(* ptrContadorFunc) ()
Puntero a la funcion que se va a llamar en la funcion Contador
Definition at line 51 of file systick.c.
Referenced by SystickInit().
ptrSystickFunc
void(* ptrSystickFunc) ()
Puntero a la funcion que se va a llamar en la interrupcion del systick
Definition at line 50 of file systick.c.
Referenced by SysTick_Handler(), and SystickInit().