Proyecto 1: PWM sct
PWM sct
Drivers Programable » Drivers microcontroller
Enumerations
enum pwm_out_t { CTOUT0 = 0, CTOUT1, CTOUT2, CTOUT3 }
Functions
bool PWMInit (pwm_out_t *ctout, uint8_t n_outs, uint16_t freq)
Initialization function param[in] ctout vector with the outputs pin param[in] n_outs number of outputs param[in] freq Frequency of ALL PWM outputs.
void PWMOn (void)
Function to turn on PWM outputs.
void PWMOff (void)
Function to turn off PWM outputs.
void PWMSetDutyCycle (pwm_out_t ctout, uint8_t duty_cycle)
Function to change PWM duty cycle of an output param[in] ctout Output pin param[in] duty_cycle Duty cycle of PWM.
bool PWMSetFreq (uint32_t freq)
Function to set freq of all PWM outputs param[in] freq Frequency of PWM.
bool PWMDeinit (void)
Function to turn off PWM.
Detailed Description
Enumeration Type Documentation
pwm_out_t
enum pwm_out_t
Enumerator
CTOUT0
Located in TFIL_2
CTOUT1
Located in TFIL_1
CTOUT2
Located in LCD1
CTOUT3
Located in TFIL_3
Definition at line 55 of file pwm_sct.h.
Function Documentation
PWMDeinit()
bool PWMDeinit (void)
Function to turn off PWM.
Returns
TRUE if no error
Definition at line 134 of file pwm_sct.c.
Referenced by BuzzerDeinit().
PWMInit()
bool PWMInit (pwm_out_t * ctout, uint8_t n_outs, uint16_t freq)
Initialization function param[in] ctout vector with the outputs pin param[in] n_outs number of outputs param[in] freq Frequency of ALL PWM outputs.
Returns
TRUE if no error
Definition at line 90 of file pwm_sct.c.
Referenced by BuzzerInit().
PWMSetFreq()
bool PWMSetFreq (uint32_t freq)
Function to set freq of all PWM outputs param[in] freq Frequency of PWM.
Returns
TRUE if no error
Definition at line 123 of file pwm_sct.c.
Referenced by BuzzerSetFrec(), and playTone().