Proyecto 1: LCD ITSE0803
LCD ITSE0803
Drivers Programable » Drivers devices
Files
file lcditse0803.h
Functions
bool LcdItsE0803Init (void)
Initialization function of EDU-CIAA LCD Modules.
bool LcdItsE0803Write (uint16_t value)
Function to display value a LCD Module for EDU-CIAA.
uint16_t LcdItsE0803Read (void)
Function to read a number in LCD Module.
void LcdItsE0803Off (void)
Function to turn off LCD Module.
bool LcdItsE0803DeInit (void)
DeInitialization function of EDU-CIAA LCD Module.
Detailed Description
Function Documentation
LcdItsE0803DeInit()
bool LcdItsE0803DeInit (void)
DeInitialization function of EDU-CIAA LCD Module.
Returns
TRUE if no error
Definition at line 163 of file lcditse0803.c.
References GPIODeinit().
LcdItsE0803Init()
bool LcdItsE0803Init (void)
Initialization function of EDU-CIAA LCD Modules.
Returns
TRUE if no error
Definition at line 77 of file lcditse0803.c.
LcdItsE0803Read()
uint16_t LcdItsE0803Read (void)
Function to read a number in LCD Module.
Returns
number in LCD Module
Definition at line 142 of file lcditse0803.c.
LcdItsE0803Write()
bool LcdItsE0803Write (uint16_t value)
Function to display value a LCD Module for EDU-CIAA.
Parameters
[in] value to show 0..999
Returns
false if an error occurs (out of scale), in other case returns true
Definition at line 108 of file lcditse0803.c.
References GPIO_1, GPIO_3, GPIO_5, GPIOOff(), and GPIOOn().