Proyecto 1: HC SR04
HC SR04
Drivers Programable » Drivers devices
Functions
bool HcSr04Init (gpio_t echo, gpio_t trigger)
Initialization function of HC_SR04.
uint16_t HcSr04ReadDistanceInCentimeters (void)
Function to measure the distance in centimeters.
uint16_t HcSr04ReadDistanceInInches (void)
Function to measure the distance in inches.
bool HcSr04Deinit (void)
Function to deinitialize HC_SR04 driver.
Detailed Description
Function Documentation
HcSr04Deinit()
bool HcSr04Deinit (void)
Function to deinitialize HC_SR04 driver.
Returns
TRUE if no error
Definition at line 125 of file hc_sr04.c.
References GPIODeinit().
HcSr04Init()
bool HcSr04Init (gpio_t echo, gpio_t trigger)
Initialization function of HC_SR04.
Parameters
[in] echo pin GPIO where is connected echo port of peripheral
[in] trigger pin GPIO where is connected trigger port of peripheral
Returns
TRUE if no error
Configuration of the GPIO pins
Definition at line 75 of file hc_sr04.c.
HcSr04ReadDistanceInCentimeters()
uint16_t HcSr04ReadDistanceInCentimeters (void)
Function to measure the distance in centimeters.
Returns
distance in centimeters
Definition at line 87 of file hc_sr04.c.
References DelayUs(), GPIOOff(), GPIOOn(), and GPIORead().
HcSr04ReadDistanceInInches()
uint16_t HcSr04ReadDistanceInInches (void)
Function to measure the distance in inches.
Returns
distance in inches
Definition at line 106 of file hc_sr04.c.
References DelayUs(), GPIOOff(), GPIOOn(), and GPIORead().