Proyecto 1: MMA7260Q
MMA7260Q
Drivers Programable » Drivers devices
Enumerations
enum mma7260_range_t { MMA7260_RANGE_1_5G = 0, MMA7260_RANGE_2G, MMA7260_RANGE_4G, MMA7260_RANGE_6G }
driver que maneja la lectura de datos obtenida a partir de un acelerómetro.
Functions
bool MMA7260QInit (gpio_t gSelect1, gpio_t gSelect2, mma7260_range_t range)
float ReadXValue ()
Función que lee el pin x del driver y devuelve el valor convertido de analógico a digital en unidades de gravedad.
float ReadYValue ()
Función que lee el pin y del driver y devuelve el valor convertido de analógico a digital en unidades de gravedad.
float ReadZValue ()
Función que lee el pin z del driver y devuelve el valor convertido de analógico a digital en unidades de gravedad.
bool MMA7260QDeinit (gpio_t gSelect1, gpio_t gSelect2)
Función que de-inicializa los pines de selección del driver.
int ReadXValueInt ()
int ReadYValueInt ()
int ReadZValueInt ()
Detailed Description
Function Documentation
MMA7260QDeinit()
bool MMA7260QDeinit (gpio_t gSelect1, gpio_t gSelect2)
Función que de-inicializa los pines de selección del driver.
Parameters
[in] gSelect1
[in] gSelect2
Returns
1 (true) if no error
ReadXValue()
float ReadXValue ()
Función que lee el pin x del driver y devuelve el valor convertido de analógico a digital en unidades de gravedad.
Parameters
[in] No hay parámetros
Returns
Aceleración en el eje x
Definition at line 175 of file MMA7260Q.c.
References AnalogInputInit().
ReadYValue()
float ReadYValue ()
Función que lee el pin y del driver y devuelve el valor convertido de analógico a digital en unidades de gravedad.
Parameters
[in] No hay parámetros
Returns
Aceleración en el eje y
Definition at line 201 of file MMA7260Q.c.
References AnalogInputInit().
ReadZValue()
float ReadZValue ()
Función que lee el pin z del driver y devuelve el valor convertido de analógico a digital en unidades de gravedad.
Parameters
[in] No hay parámetros
Returns
Aceleración en el eje z
Definition at line 227 of file MMA7260Q.c.
References AnalogInputInit().