Proyecto 1: Delay
Delay
Drivers Programable » Drivers devices
Functions
void DelaySec (uint32_t sec)
Delay in seconds.
void DelayMs (uint32_t msec)
Delay in milliseconds.
void DelayUs (uint32_t usec)
Delay in microseconds.
Detailed Description
Function Documentation
DelayMs()
void DelayMs (uint32_t msec)
Delay in milliseconds.
Parameters
[in] msec milliseconds to be in delay
Returns
None
Definition at line 52 of file delay.c.
Referenced by DelaySec(), and playTone().
DelaySec()
void DelaySec (uint32_t sec)
Delay in seconds.
Parameters
[in] sec seconds to be in delay
Returns
None
Definition at line 47 of file delay.c.
References DelayMs().
DelayUs()
void DelayUs (uint32_t usec)
Delay in microseconds.
Parameters
[in] usec microseconds to be in delay
Returns
None
Definition at line 65 of file delay.c.
Referenced by HcSr04ReadDistanceInCentimeters(), and HcSr04ReadDistanceInInches().