Proyecto 1: GPIO
GPIO
Bare Metal driver for gpio in the EDU-CIAA board.
Data Structures
struct digitalIO
Functions
void GPIO0_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO1_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO2_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO3_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO4_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO5_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO6_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GPIO7_IRQHandler (void)
Interruption function of a gpio entry. Call the indicated function.
void GINT0_IRQHandler (void)
Interruption function of a group of gpio entries. Call the indicated function.
void GPIOInit (gpio_t pin, io_t io)
void GPIOOn (gpio_t pin)
Pone a 1 un pin de la EDU-CIAA.
void GPIOOff (gpio_t pin)
Apaga un pin de la EDU-CIAA.
void GPIOState (gpio_t pin, bool state)
void GPIOToggle (gpio_t pin)
Invierte el estado de un pin de la EDU-CIAA.
bool GPIORead (gpio_t pin)
Lectura de un pin de la EDU-CIAA.
void GPIOActivInt (gpiogp_t gp, gpio_t pin, void *ptr_int_func, bool edge)
Activa la interrupcion de un pin en particular y se la asigna a un grupo de interrupciones definido en gpiogp_t.
void GPIOActivGroupInt (gpiogroupgp_t group_gp, gpio_t *pins, uint8_t n_pins, void *ptr_int_func, bool edge)
Activate group interrupts and add to the interruption the chosen gpio through the vector.
void GINT1_IRQHandler (void)
void GPIODeinit (void)
Deinicializacion de los puertos GPIO de la EDU-CIAA.
Variables
const digitalIO gpio []
void(* ptr_GPIO_int_func [8])()
void(* ptr_GPIO_group_int_func [2])()
Detailed Description
Bare Metal driver for gpio in the EDU-CIAA board.
/**
Function Documentation
GPIOActivGroupInt()
void GPIOActivGroupInt (gpiogroupgp_t group_gp, gpio_t * pins, uint8_t n_pins, void * ptr_int_func, bool edge)
Activate group interrupts and add to the interruption the chosen gpio through the vector.
Parameters
[in] group_gp
[in] pins
[in] n_pins
[in] ptrIntFunc Function to be called in the interruption.
[in] edge
Definition at line 210 of file gpio.c.
References Chip_GPIOGP_SelectOrMode(), and ptr_GPIO_group_int_func.
GPIOActivInt()
void GPIOActivInt (gpiogp_t gp, gpio_t pin, void * ptr_int_func, bool edge)
Activa la interrupcion de un pin en particular y se la asigna a un grupo de interrupciones definido en gpiogp_t.
Parameters
[in] gp Indica a que grupo de interrupciones se asigna al pin
[in] pin Pin que va a interrumpir
[in] void *ptr_int_func Funcion a la que se va a llamar en la interrupcion
[in] bool edge 1 si es flanco ascendente y 0 si es descendente
Definition at line 193 of file gpio.c.
References Chip_SCU_GPIOIntPinSel(), and ptr_GPIO_int_func.
GPIOOff()
void GPIOOff (gpio_t pin)
Apaga un pin de la EDU-CIAA.
Parameters
[in] pin Pin que se desea poner a 0
Definition at line 173 of file gpio.c.
References Chip_GPIO_SetPinOutLow().
Referenced by LedsOffAll().
GPIOOn()
void GPIOOn (gpio_t pin)
Pone a 1 un pin de la EDU-CIAA.
Parameters
[in] pin Pin que se desea poner a 1
Definition at line 168 of file gpio.c.
References Chip_GPIO_SetPinOutHigh().
GPIORead()
bool GPIORead (gpio_t pin)
Lectura de un pin de la EDU-CIAA.
Parameters
[in] pin Pin a leer el estado
Returns
Booleano que indica el estado del pin
Definition at line 188 of file gpio.c.
References Chip_GPIO_ReadPortBit().
Referenced by SwitchesRead().
GPIOToggle()
void GPIOToggle (gpio_t pin)
Invierte el estado de un pin de la EDU-CIAA.
Parameters
[in] pin Pin que se desea invertir
Definition at line 183 of file gpio.c.
References Chip_GPIO_SetPinToggle().
Variable Documentation
gpio
const digitalIO gpio[]
Initial value:
=
{
    {0x01, 0x00, 0x00, 0x04, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x01, 0x01, 0x00, 0x08, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x01, 0x02, 0x00, 0x09, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x01, 0x06, 0x01, 0x09, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x02, 0x0A, 0x00, 0x0E, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x02, 0x0B, 0x01, 0x0B, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x02, 0x0C, 0x01, 0x0C, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x02, 0x00, 0x05, 0x00, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x02, 0x01, 0x05, 0x01, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x02, 0x02, 0x05, 0x02, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x04, 0x04, 0x02, 0x04, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x05, 0x02, 0x05, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x06, 0x02, 0x06, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x0A, 0x05, 0x0E, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x06, 0x04, 0x03, 0x03, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x06, 0x07, 0x05, 0x0F, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x06, 0x09, 0x03, 0x05, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x09, 0x05, 0x0D, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x04, 0x08, 0x05, 0x0C, MD_PUP|MD_EZI|MD_ZI|FUNC4},
    {0x01, 0x05, 0x01, 0x08, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x07, 0x04, 0x03, 0x0C, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x00, 0x02, 0x00, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x02, 0x02, 0x02, MD_PUP|MD_EZI|MD_ZI|FUNC0},
    {0x04, 0x03, 0x02, 0x03, MD_PUP|MD_EZI|MD_ZI|FUNC0}
}
Definition at line 121 of file gpio.c.
ptr_GPIO_group_int_func
void(* ptr_GPIO_group_int_func[2])()
Pointer to the function to be called at the interruption of a group of GPIOs
Definition at line 151 of file gpio.c.
Referenced by GPIOActivGroupInt().
ptr_GPIO_int_func
void(* ptr_GPIO_int_func[8])()
Pointer to the function to be called at the interruption of each GPIO
Definition at line 150 of file gpio.c.
Referenced by GPIO0_IRQHandler(), GPIO1_IRQHandler(), GPIO2_IRQHandler(), GPIO3_IRQHandler(), GPIO4_IRQHandler(), GPIO5_IRQHandler(), GPIO6_IRQHandler(), GPIO7_IRQHandler(), and GPIOActivInt().