Proyecto 1: CHIP: LPC18xx/43xx EEPROM driver
CHIP: LPC18xx/43xx EEPROM driver
Data Structures
struct LPC_EEPROM_T
EEPROM register block structure.
Macros
#define EEPROM_START (0x20040000)
#define EEPROM_PAGE_SIZE (128)
#define EEPROM_PAGE_NUM (128)
#define EEPROM_ADDRESS(page, offset) (EEPROM_START + (EEPROM_PAGE_SIZE * (page)) + offset)
#define EEPROM_CLOCK_DIV 1500000
#define EEPROM_READ_WAIT_STATE_VAL 0x58
#define EEPROM_WAIT_STATE_VAL 0x232
#define EEPROM_CMD_ERASE_PRG_PAGE (6)
#define EEPROM_AUTOPROG_OFF (0)
#define EEPROM_AUTOPROG_AFT_1WORDWRITTEN (1)
#define EEPROM_AUTOPROG_AFT_LASTWORDWRITTEN (2)
#define EEPROM_PWRDWN (1 << 0)
#define EEPROM_INT_ENDOFPROG (1 << 2)
Functions
STATIC INLINE void Chip_EEPROM_EnablePowerDown (LPC_EEPROM_T *pEEPROM)
Put EEPROM device in power down mode.
STATIC INLINE void Chip_EEPROM_DisablePowerDown (LPC_EEPROM_T *pEEPROM)
Bring EEPROM device out of power down mode.
void Chip_EEPROM_Init (LPC_EEPROM_T *pEEPROM)
Initializes EEPROM.
STATIC INLINE void Chip_EEPROM_DeInit (LPC_EEPROM_T *pEEPROM)
De-initializes EEPROM.
STATIC INLINE void Chip_EEPROM_SetAutoProg (LPC_EEPROM_T *pEEPROM, uint32_t mode)
Set Auto program mode.
STATIC INLINE void Chip_EEPROM_SetReadWaitState (LPC_EEPROM_T *pEEPROM, uint32_t ws)
Set EEPROM Read Wait State.
STATIC INLINE void Chip_EEPROM_SetWaitState (LPC_EEPROM_T *pEEPROM, uint32_t ws)
Set EEPROM wait state.
STATIC INLINE void Chip_EEPROM_SetCmd (LPC_EEPROM_T *pEEPROM, uint32_t cmd)
Select an EEPROM command.
void Chip_EEPROM_EraseProgramPage (LPC_EEPROM_T *pEEPROM)
Erase/Program an EEPROM page.
void Chip_EEPROM_WaitForIntStatus (LPC_EEPROM_T *pEEPROM, uint32_t mask)
Wait for interrupt occurs.
STATIC INLINE void Chip_EEPROM_EnableInt (LPC_EEPROM_T *pEEPROM, uint32_t mask)
Enable EEPROM interrupt.
STATIC INLINE void Chip_EEPROM_DisableInt (LPC_EEPROM_T *pEEPROM, uint32_t mask)
Disable EEPROM interrupt.
STATIC INLINE uint32_t Chip_EEPROM_GetIntEnable (LPC_EEPROM_T *pEEPROM)
Get the value of the EEPROM interrupt enable register.
STATIC INLINE uint32_t Chip_EEPROM_GetIntStatus (LPC_EEPROM_T *pEEPROM)
Get EEPROM interrupt status.
STATIC INLINE void Chip_EEPROM_SetIntStatus (LPC_EEPROM_T *pEEPROM, uint32_t mask)
Set EEPROM interrupt status.
STATIC INLINE void Chip_EEPROM_ClearIntStatus (LPC_EEPROM_T *pEEPROM, uint32_t mask)
Clear EEPROM interrupt status.
Detailed Description
Macro Definition Documentation
EEPROM_ADDRESS
#define EEPROM_ADDRESS (page, offset) (EEPROM_START + (EEPROM_PAGE_SIZE * (page)) + offset)
Get the eeprom address
Definition at line 52 of file eeprom_18xx_43xx.h.
EEPROM_AUTOPROG_AFT_1WORDWRITTEN
#define EEPROM_AUTOPROG_AFT_1WORDWRITTEN (1)
Erase/program cycle is triggered after 1 word is written
Definition at line 86 of file eeprom_18xx_43xx.h.
EEPROM_AUTOPROG_AFT_LASTWORDWRITTEN
#define EEPROM_AUTOPROG_AFT_LASTWORDWRITTEN (2)
Erase/program cycle is triggered after a write to AHB address ending with ......1111100 (last word of a page)
Definition at line 88 of file eeprom_18xx_43xx.h.
EEPROM_AUTOPROG_OFF
#define EEPROM_AUTOPROG_OFF (0)
Auto programming off
Definition at line 85 of file eeprom_18xx_43xx.h.
EEPROM_CMD_ERASE_PRG_PAGE
#define EEPROM_CMD_ERASE_PRG_PAGE (6)
EEPROM erase/program command
Definition at line 80 of file eeprom_18xx_43xx.h.
EEPROM_PAGE_NUM
#define EEPROM_PAGE_NUM (128)
The number of EEPROM pages. The last page is not writable.
Definition at line 50 of file eeprom_18xx_43xx.h.
EEPROM_PAGE_SIZE
#define EEPROM_PAGE_SIZE (128)
EEPROM byes per page
Definition at line 48 of file eeprom_18xx_43xx.h.
EEPROM_START
#define EEPROM_START (0x20040000)
EEPROM start address
Definition at line 46 of file eeprom_18xx_43xx.h.
Function Documentation
Chip_EEPROM_ClearIntStatus()
STATIC INLINE void Chip_EEPROM_ClearIntStatus (LPC_EEPROM_T * pEEPROM, uint32_t mask)
Clear EEPROM interrupt status.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
mask : Interrupt mask (or-ed bits value of EEPROM_INT_*)
Returns
Nothing
Definition at line 262 of file eeprom_18xx_43xx.h.
Referenced by Chip_EEPROM_EraseProgramPage(), and Chip_EEPROM_WaitForIntStatus().
Chip_EEPROM_DeInit()
STATIC INLINE void Chip_EEPROM_DeInit (LPC_EEPROM_T * pEEPROM)
De-initializes EEPROM.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
Returns
Nothing
Definition at line 132 of file eeprom_18xx_43xx.h.
Chip_EEPROM_DisableInt()
STATIC INLINE void Chip_EEPROM_DisableInt (LPC_EEPROM_T * pEEPROM, uint32_t mask)
Disable EEPROM interrupt.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
mask : Interrupt mask (or-ed bits value of EEPROM_INT_*)
Returns
Nothing
Definition at line 220 of file eeprom_18xx_43xx.h.
Chip_EEPROM_DisablePowerDown()
STATIC INLINE void Chip_EEPROM_DisablePowerDown (LPC_EEPROM_T * pEEPROM)
Bring EEPROM device out of power down mode.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
Returns
Nothing
Definition at line 115 of file eeprom_18xx_43xx.h.
Referenced by Chip_EEPROM_Init().
Chip_EEPROM_EnableInt()
STATIC INLINE void Chip_EEPROM_EnableInt (LPC_EEPROM_T * pEEPROM, uint32_t mask)
Enable EEPROM interrupt.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
mask : Interrupt mask (or-ed bits value of EEPROM_INT_*)
Returns
Nothing
Definition at line 209 of file eeprom_18xx_43xx.h.
Chip_EEPROM_EnablePowerDown()
STATIC INLINE void Chip_EEPROM_EnablePowerDown (LPC_EEPROM_T * pEEPROM)
Put EEPROM device in power down mode.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
Returns
Nothing
Definition at line 105 of file eeprom_18xx_43xx.h.
Chip_EEPROM_EraseProgramPage()
void Chip_EEPROM_EraseProgramPage (LPC_EEPROM_T * pEEPROM)
Erase/Program an EEPROM page.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
Returns
Nothing
Definition at line 81 of file eeprom_18xx_43xx.c.
References Chip_EEPROM_ClearIntStatus(), Chip_EEPROM_SetCmd(), Chip_EEPROM_WaitForIntStatus(), and EEPROM_CMD_ERASE_PRG_PAGE.
Chip_EEPROM_GetIntEnable()
STATIC INLINE uint32_t Chip_EEPROM_GetIntEnable (LPC_EEPROM_T * pEEPROM)
Get the value of the EEPROM interrupt enable register.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
Returns
OR-ed bits value of EEPROM_INT_*
Definition at line 230 of file eeprom_18xx_43xx.h.
Chip_EEPROM_GetIntStatus()
STATIC INLINE uint32_t Chip_EEPROM_GetIntStatus (LPC_EEPROM_T * pEEPROM)
Get EEPROM interrupt status.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
Returns
OR-ed bits value of EEPROM_INT_*
Definition at line 240 of file eeprom_18xx_43xx.h.
Referenced by Chip_EEPROM_WaitForIntStatus().
Chip_EEPROM_Init()
void Chip_EEPROM_Init (LPC_EEPROM_T * pEEPROM)
Initializes EEPROM.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
Returns
Nothing
Definition at line 72 of file eeprom_18xx_43xx.c.
References Chip_EEPROM_DisablePowerDown().
Chip_EEPROM_SetAutoProg()
STATIC INLINE void Chip_EEPROM_SetAutoProg (LPC_EEPROM_T * pEEPROM, uint32_t mode)
Set Auto program mode.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
mode : Auto Program Mode (One of EEPROM_AUTOPROG_* value)
Returns
Nothing
Definition at line 144 of file eeprom_18xx_43xx.h.
Chip_EEPROM_SetCmd()
STATIC INLINE void Chip_EEPROM_SetCmd (LPC_EEPROM_T * pEEPROM, uint32_t cmd)
Select an EEPROM command.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
cmd : EEPROM command
Returns
Nothing
Note
The cmd is OR-ed bits value of EEPROM_CMD_*
Definition at line 183 of file eeprom_18xx_43xx.h.
Referenced by Chip_EEPROM_EraseProgramPage().
Chip_EEPROM_SetIntStatus()
STATIC INLINE void Chip_EEPROM_SetIntStatus (LPC_EEPROM_T * pEEPROM, uint32_t mask)
Set EEPROM interrupt status.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
mask : Interrupt mask (or-ed bits value of EEPROM_INT_*)
Returns
Nothing
Definition at line 251 of file eeprom_18xx_43xx.h.
Chip_EEPROM_SetReadWaitState()
STATIC INLINE void Chip_EEPROM_SetReadWaitState (LPC_EEPROM_T * pEEPROM, uint32_t ws)
Set EEPROM Read Wait State.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
ws : Wait State value
Returns
Nothing
Note
Bits 7:0 represents wait state for Read Phase 2 and Bits 15:8 represents wait state for Read Phase1
Definition at line 157 of file eeprom_18xx_43xx.h.
Chip_EEPROM_SetWaitState()
STATIC INLINE void Chip_EEPROM_SetWaitState (LPC_EEPROM_T * pEEPROM, uint32_t ws)
Set EEPROM wait state.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
ws : Wait State value
Returns
Nothing
Note
Bits 7:0 represents wait state for Phase 3, Bits 15:8 represents wait state for Phase2, and Bits 23:16 represents wait state for Phase1
Definition at line 171 of file eeprom_18xx_43xx.h.
Chip_EEPROM_WaitForIntStatus()
void Chip_EEPROM_WaitForIntStatus (LPC_EEPROM_T * pEEPROM, uint32_t mask)
Wait for interrupt occurs.
Parameters
pEEPROM : Pointer to EEPROM peripheral block structure
mask : Expected interrupt
Returns
Nothing
Definition at line 89 of file eeprom_18xx_43xx.c.
References Chip_EEPROM_ClearIntStatus(), and Chip_EEPROM_GetIntStatus().
Referenced by Chip_EEPROM_EraseProgramPage().