var modules =
[
    [ "CHIP:  LPC18xx/43xx A/D conversion driver", "group___a_d_c__18_x_x__43_x_x.html", "group___a_d_c__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx AES Engine driver", "group___a_e_s__18_x_x__43_x_x.html", "group___a_e_s__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Alarm Timer driver", "group___a_t_i_m_e_r__18_x_x__43_x_x.html", "group___a_t_i_m_e_r__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx CCAN driver", "group___c_c_a_n__18_x_x__43_x_x.html", "group___c_c_a_n__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx support functions", "group___s_u_p_p_o_r_t__18_x_x__43_x_x___f_u_n_c.html", "group___s_u_p_p_o_r_t__18_x_x__43_x_x___f_u_n_c" ],
    [ "CHIP: LPC18xx Peripheral addresses and register set declarations", "group___p_e_r_i_p_h__18_x_x___b_a_s_e.html", null ],
    [ "CHIP: LPC43xx Peripheral addresses and register set declarations", "group___p_e_r_i_p_h__43_x_x___b_a_s_e.html", null ],
    [ "CHIP: LPC18xx/43xx Clock Driver", "group___c_l_o_c_k__18_x_x__43_x_x.html", "group___c_l_o_c_k__18_x_x__43_x_x" ],
    [ "CHIP: LPC43xx CMSIS include file", "group___c_m_s_i_s__43_x_x.html", "group___c_m_s_i_s__43_x_x" ],
    [ "CMSIS Global Defines", "group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group___c_m_s_i_s__core__register.html", "group___c_m_s_i_s__core__register" ],
    [ "CMSIS SIMD Intrinsics", "group___c_m_s_i_s___s_i_m_d__intrinsics.html", null ],
    [ "CMSIS Core Instruction Interface", "group___c_m_s_i_s___core___instruction_interface.html", null ],
    [ "CHIP: LPC18xx/43xx CREG driver", "group___c_r_e_g__18_x_x__43_x_x.html", "group___c_r_e_g__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx D/A conversion driver", "group___d_a_c__18_x_x__43_x_x.html", "group___d_a_c__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx EEPROM driver", "group___e_e_p_r_o_m__18_x_x__43_x_x.html", "group___e_e_p_r_o_m__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx External Memory Controller driver", "group___e_m_c__18_x_x__43_x_x.html", "group___e_m_c__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Ethernet driver", "group___e_n_e_t__18_x_x__43_x_x.html", "group___e_n_e_t__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Event router driver", "group___e_v_r_t__18_x_x__43_x_x.html", "group___e_v_r_t__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx FLASH Memory Controller driver", "group___f_m_c__18_x_x__43_x_x.html", "group___f_m_c__18_x_x__43_x_x" ],
    [ "CHIP: FPU initialization", "group___c_h_i_p___f_p_u___c_m_x.html", "group___c_h_i_p___f_p_u___c_m_x" ],
    [ "CHIP: LPC18xx/43xx GIMA driver", "group___g_i_m_a__18_x_x__43_x_x.html", "group___g_i_m_a__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx General Purpose DMA driver", "group___g_p_d_m_a__18_x_x__43_x_x.html", "group___g_p_d_m_a__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx GPIO driver", "group___g_p_i_o__18_x_x__43_x_x.html", "group___g_p_i_o__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx GPIO group driver", "group___g_p_i_o_g_p__18_x_x__43_x_x.html", "group___g_p_i_o_g_p__18_x_x__43_x_x" ],
    [ "CHIP:  LPC18xx/43xx High speed ADC driver", "group___h_s_a_d_c__18_x_x__43_x_x.html", "group___h_s_a_d_c__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx_43xx I2C driver", "group___i2_c__18_x_x__43_x_x.html", "group___i2_c__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx I2S driver", "group___i2_s__18_x_x__43_x_x.html", "group___i2_s__18_x_x__43_x_x" ],
    [ "CHIP: Common Chip ISP/IAP commands and return codes", "group___c_o_m_m_o_n___i_a_p.html", "group___c_o_m_m_o_n___i_a_p" ],
    [ "CHIP: LPC18xx/43xx Flash IAP driver", "group___i_a_p__18_x_x__43_x_x.html", "group___i_a_p__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx LCD driver", "group___l_c_d__18_x_x__43_x_x.html", "group___l_c_d__18_x_x__43_x_x" ],
    [ "CHIP: LPC Common Types", "group___l_p_c___types.html", "group___l_p_c___types" ],
    [ "CHIP: LPC18xx/43xx Motor Control PWM driver", "group___m_c_p_w_m__18_x_x__43_x_x.html", "group___m_c_p_w_m__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx OTP Controller driver", "group___o_t_p__18_x_x__43_x_x.html", "group___o_t_p__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Pin Interrupt and Pattern Match driver", "group___p_i_n_i_n_t__18_x_x__43_x_x.html", "group___p_i_n_i_n_t__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Power Management Controller driver", "group___p_m_c__18_x_x__43_x_x.html", "group___p_m_c__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Quadrature Encoder Interface driver", "group___q_e_i__18_x_x__43_x_x.html", "group___q_e_i__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Reset Generator Unit (RGU) driver", "group___r_g_u__18_x_x__43_x_x.html", "group___r_g_u__18_x_x__43_x_x" ],
    [ "CHIP: Simple ring buffer implementation", "group___ring___buffer.html", "group___ring___buffer" ],
    [ "CHIP: LPC18xx/43xx Repetitive Interrupt Timer driver", "group___r_i_t_i_m_e_r__18_x_x__43_x_x.html", "group___r_i_t_i_m_e_r__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx_43xx ROM API declarations and functions", "group___r_o_m_a_p_i__18_x_x__43_x_x.html", "group___r_o_m_a_p_i__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Real Time Clock driver", "group___r_t_c__18_x_x__43_x_x.html", "group___r_t_c__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx State Configurable Timer driver", "group___s_c_t__18_x_x__43_x_x.html", "group___s_c_t__18_x_x__43_x_x" ],
    [ "CHIP: LPC18XX_43XX State Configurable Timer PWM driver", "group___s_c_t___p_w_m__18_x_x__43_x_x.html", "group___s_c_t___p_w_m__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx SCU Driver (configures pin functions)", "group___s_c_u__18_x_x__43_x_x.html", "group___s_c_u__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx SD/SDIO driver", "group___s_d_i_f__18_x_x__43_x_x.html", "group___s_d_i_f__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx SDIO Card driver", "group___s_d_i_o__18_x_x__43_x_x.html", "group___s_d_i_o__18_x_x__43_x_x" ],
    [ "CHIP: Common SD/MMC definitions", "group___c_h_i_p___s_d_m_m_c___definitions.html", "group___c_h_i_p___s_d_m_m_c___definitions" ],
    [ "CHIP: LPC18xx/43xx SD/MMC driver", "group___s_d_m_m_c__18_x_x__43_x_x.html", "group___s_d_m_m_c__18_x_x__43_x_x" ],
    [ "CHIP: LPC43xx Serial GPIO driver", "group___s_g_p_i_o__43_x_x.html", null ],
    [ "CHIP: LPC43xx SPI driver", "group___s_p_i__43_x_x.html", null ],
    [ "CHIP: LPC18xx/43xx SSP driver", "group___s_s_p__18_x_x__43_x_x.html", "group___s_s_p__18_x_x__43_x_x" ],
    [ "CHIP: Stopwatch primitives.", "group___stop___watch.html", "group___stop___watch" ],
    [ "CHIP: LPC18xx/43xx 16/32-bit Timer driver", "group___t_i_m_e_r__18_x_x__43_x_x.html", "group___t_i_m_e_r__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx UART driver", "group___u_a_r_t__18_x_x__43_x_x.html", "group___u_a_r_t__18_x_x__43_x_x" ],
    [ "Communication Device Class (CDC) Function Driver", "group___u_s_b_d___c_d_c.html", "group___u_s_b_d___c_d_c" ],
    [ "USB Core Layer", "group___u_s_b_d___core.html", "group___u_s_b_d___core" ],
    [ "Device Firmware Upgrade (DFU) Class Function Driver", "group___u_s_b_d___d_f_u.html", "group___u_s_b_d___d_f_u" ],
    [ "HID Class Function Driver", "group___u_s_b_d___h_i_d.html", "group___u_s_b_d___h_i_d" ],
    [ "USB Device Controller Driver", "group___u_s_b_d___h_w.html", "group___u_s_b_d___h_w" ],
    [ "Mass Storage Class (MSC) Function Driver", "group___u_s_b_d___m_s_c.html", "group___u_s_b_d___m_s_c" ],
    [ "CHIP: LPC18xx/43xx USBHS Device, Host, & OTG driver", "group___u_s_b_h_s__18_x_x__43_x_x.html", "group___u_s_b_h_s__18_x_x__43_x_x" ],
    [ "CHIP: LPC18xx/43xx Windowed Watchdog driver", "group___w_w_d_t__18_x_x__43_x_x.html", "group___w_w_d_t__18_x_x__43_x_x" ],
    [ "Drivers Programable", "group___drivers___programable.html", "group___drivers___programable" ],
    [ "GPIO", "group___g_p_i_o.html", "group___g_p_i_o" ]
];